### ISSUE TITLE
Export does not export Amount in USD column to CSV

### ISSUE THREAD

**Issue by adam248** [bitfinexcom/bfx-report-electron#114]
Simply when you go to the ledger page you can see the Amount in USD as well as the Currency.
![image](https://user-images.githubusercontent.com/85082674/131928037-3ca39220-3930-42b9-be6d-3950fe5ee488.png)

But when you try to export it, that column is missing from the CSV file:
![image](https://user-images.githubusercontent.com/85082674/131928097-350d5f66-ce7b-4cbf-81f0-3b4ddffcc2ed.png)

Thank you.

**Comment by ezewer** [comment]
@adam248 we would add this feature.

**Comment by ezewer** [comment]
@adam248 this has been added on last release, version 3.6.3
