### ISSUE TITLE
[BUG REPORT] W10 / EACCES: permission denied 0.0.0.0:1455

### ISSUE THREAD

**Issue by Nementon** [bitfinexcom/bfx-report-electron#171]
An error occurred

```vim
AppInitializationError: ERR_APP_HAS_NOT_INITIALIZED
    at Timeout.<anonymous> (C:/Users/Admin/AppData/Local/Programs/bfx-report-electron/resources/app/src/initialize-app.js:110:16)
```

---

| Debug info | |
| :--- | :--- |
| Version | 3.8.1 |
| Commit Hash | cbdd94642b7c23c2aceedd34367d1e79a07fc4e4 |
| Commit Date | 2022-09-30T02:51:16Z |
| Electron | 13.6.9 |
| Chrome | 91.0.4472.164 |
| Node.js | 14.16.0 |
| V8 | 9.1.269.40-electron.0 |
| OS version | Windows 10 Pro |
| OS release | Windows_NT x64 10.0.19045 |
| CPUs | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz x 4 |
| RAM | 19.84GB (10.01GB free) |
| App RAM limit | 4095.75Mb (8.33MB used) |

<details>

<summary>Main log</summary>

```vim
[2022-11-30 22:43:
[2022-11-30 23:07:07.475] [error] AppInitializationError: ERR_APP_HAS_NOT_INITIALIZED
    at Timeout.<anonymous> (C:/Users/Admin/AppData/Local/Programs/bfx-report-electron/resources/app/src/initialize-app.js:110:16)

```

</details>

<details>

<summary>Worker errors</summary>

```vim
Empty
```

</details>

<details>

<summary>Worker exceptions</summary>

```vim
WORKER:ERROR [2022-11-30T21:57:13.031Z] uncaughtException: listen EACCES: permission denied 0.0.0.0:1455
Error: listen EACCES: permission denied 0.0.0.0:1455
    at Server.setupListenHandle [as _listen2] (net.js:1301:21)
    at listenI

```

</details>

---

*The issue was opened from the electron app*

NB: The issue occurs with or without administrator perms.

**Comment by ezewer** [comment]
Hi @Nementon, we are checking, would come back with more details.

**Comment by ezewer** [comment]
@Nementon when possible can confirm if the last version fixes the issue?

**Comment by Nementon** [comment]
@ezewer sorry for the late reply, I've tested [release 4.0.0](https://github.com/bitfinexcom/bfx-report-electron/releases/download/v4.0.0/BitfinexReport-4.0.0-x64-win.exe), here what happens:

1. It showed loading screen for a little while
![image](https://user-images.githubusercontent.com/2373370/212289479-0d45574d-c73d-4c30-8f96-58b367a6e5e0.png)
2. Acknowledged for successful DB backup
![image](https://user-images.githubusercontent.com/2373370/212289569-c3beab7f-ee2a-4fcb-80c7-246ecde639e0.png)
3. It showed loading screen for a while again, way longer (~>= 5mins)
5. It seems I had the same issue, see below for the context:

An error occurred

```vim
AppInitializationError: ERR_APP_HAS_NOT_INITIALIZED
    at Timeout.<anonymous> (C:/Users/Admin/AppData/Local/Programs/bfx-report-electron/resources/app/src/initialize-app.js:110:16)
```

---

| Debug info | |
| :--- | :--- |
| Version | 4.0.0 |
| Commit Hash | af2d6b6590c56d659a79d25e137d59bc4a81fe83 |
| Commit Date | 2022-12-14T14:14:17Z |
| Electron | 13.6.9 |
| Chrome | 91.0.4472.164 |
| Node.js | 14.16.0 |
| V8 | 9.1.269.40-electron.0 |
| OS version | Windows 10 Pro |
| OS release | Windows_NT x64 10.0.19045 |
| CPUs | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz x 4 |
| RAM | 19.84GB (11.13GB free) |
| App RAM limit | 4095.75Mb (8.68MB used) |

<details>

<summary>Main log</summary>

```vim
[2022-11-30 23:07:
[2023-01-13 10:56:14.597] [error] AppInitializationError: ERR_APP_HAS_NOT_INITIALIZED
    at Timeout.<anonymous> (C:/Users/Admin/AppData/Local/Programs/bfx-report-electron/resources/app/src/initialize-app.js:110:16)

```

</details>

<details>

<summary>Worker errors</summary>

```vim
Empty
```

</details>

<details>

<summary>Worker exceptions</summary>

```vim
WORKER:ERROR [2023-01-13T09:46:42.346Z] uncaughtException: listen EACCES: permission denied 0.0.0.0:1455
Error: listen EACCES: permission denied 0.0.0.0:1455
    at Server.setupListenHandle [as _listen2] (net.js:1301:21)
    at listenI

```

</details>

---

*The issue was opened from the electron app*

**Comment by ZIMkaRU** [comment]
It looks like a firewall or antivirus is blocking the application from accessing the port. Could you try to run the application by lowering the protection level or by disabling it?

**Comment by Nementon** [comment]
If from a powershell app, I'm trying to start an ncat server listening too `0.0.0.0:1455`, server binding is failing, due to unknow root cause: 

```
PS C:\Users\Admin> nc -l 0.0.0.0 -p 1455
Can't grab 0.0.0.0:1455 with bind
```

The same goes from Admin powershell:
```
PS C:\WINDOWS\system32> ..\..\Users\Admin\scoop\apps\netcat\current\nc64.exe -l 0.0.0.0 -p 1455
Can't grab 0.0.0.0:1455 with bind
```
I've the same behaviour when trying to listen to `127.0.0.1` rather than all interfaces `0.0.0.0`.

But, it seems that no service is using that port, from an Admin powershell:
```
PS C:\WINDOWS\system32> netstat -ano | findstr 1455
 [Empty]
 ```
 
 @ZIMkaRU With all Windows firewall disabled:
 ![image](https://user-images.githubusercontent.com/2373370/212297570-ada703f1-e7bd-45bc-a4fd-20b4f2418f68.png)

- From none Admin and Admin Powershell, I can not start ncat server listening on 0.0.0.0:1455 (same behaviour)
- When launching Bitfinex report app as none admin (my user account is not a local admin), same issue
- When launching Bitfinex report app as Admin, same issue:
![image](https://user-images.githubusercontent.com/2373370/212299801-5c5f5875-d9ce-4fcc-bab2-24f9412e1c9a.png)

It seems the port is part as an administravely TCP excluded/reserved range `1363        1462`  (from powershell admin):
```
PS C:\WINDOWS\system32> netsh interface ipv4 show excludedportrange protocol=tcp

Protocol tcp Port Exclusion Ranges

Start Port    End Port
----------    --------
      1080        1179
      1263        1362
      1363        1462
      1702        1801
      1882        1981
      1982        2081
      2182        2281
      2380        2479
      2480        2579
      2580        2679
      2680        2779
      2780        2879
      2880        2979
      2980        3079
      3081        3180
      3262        3361
      5357        5357
      5437        5536
      5537        5636
      5737        5836
      5837        5936
     24249       24348
     24349       24448
     24549       24648
     24649       24748
     50000       50059     *

* - Administered port exclusions.

PS C:\WINDOWS\system32> netsh interface ipv4 show excludedportrange protocol=udp

Protocol udp Port Exclusion Ranges

Start Port    End Port
----------    --------
     50000       50059     *
     50266       50365
     50366       50465
     50566       50665
     50666       50765
     54431       54530
     54531       54630
     54731       54830
     54831       54930
     55031       55130
     55131       55230
     55331       55430
     55529       55628
     55929       56028
     56029       56128
     56129       56228
     56229       56328
     56329       56428
     56429       56528
     56529       56628
     56629       56728
     57097       57196
     57197       57296
     57297       57396
     57397       57496

* - Administered port exclusions.
```
According to https://pomeroy.me/2020/09/solved-windows-10-forbidden-port-bind/ it is looks to be due to Hyper-V restriction. My W10 have all possible security features enabled, it is using [Virtualization based security](https://learn.microsoft.com/en-us/windows-hardware/design/device-experiences/oem-vbs), thus my W10 is running on top Hyper-V

**Comment by ZIMkaRU** [comment]
Thanks for the detailed bug report. I'll plan to install Win10 on the VirtualBox and debug the application on it. I'll keep you informed

**Comment by Nementon** [comment]
If I recall correctly, W11 enabled VBS by default (on W10 it is an optional security feature that needs to be enabled). I thinks it is likely that the issue will occurs on default W11 installation (assuming it is the root cause and W11 reserved the same set of ports)

**Comment by ZIMkaRU** [comment]
yep, that makes sense

**Comment by ZIMkaRU** [comment]
Hi @Nementon
I built a beta release of the bfx report app and put it into my repo fork:
https://github.com/ZIMkaRU/bfx-report-electron/releases/tag/v4.4.0-beta.0
Could you help to test this one on your PC, please? It would be good to understand that issue is resolved in your case. So this release added improved ports lookup:
- default ports:
  ```js
  {
    grape1DhtPort: 20002,
    grape1ApiPort: 40001,
    grape2DhtPort: 20001,
    grape2ApiPort: 30001,
    workerApiPort: 3501,
    workerWsPort: 10001,
    expressApiPort: 34343
  }
  ```
- port ranges for looking up:
  ```js
  [
    { from: 3500, to: 5000 },
    { from: 6000, to: 24000 },
    { from: 25000, to: 49990 }
  ]
  ```

**Pay attention** that the release is a beta version and auto-update is disabled in it. So after resolving the issue would be good to use releases from the main repo
And could you make sure that `34343` port is accessible on your system? The fact is that backend makes a lookup for this port but this feature has not been implemented in frontend yet (it means that if 34343 is busy the backend will take another free port and you won't be able to get past the login page, but there should still be no errors)

**Comment by Nementon** [comment]
Hi @ZIMkaRU 

Kudos, I can now start the app and connect with the API keys:
![image](https://user-images.githubusercontent.com/2373370/227784143-c9aa029b-58f4-4205-bf75-a7d392b98be9.png)

> And could you make sure that 34343 port is accessible on your system?

Looks it is the case, backend seems to have started on port `34343` (since I was able to authenticate), but just in case:
```
PS C:\Users\Nementon> curl 127.0.0.1:34343
curl : {"jsonrpc":"2.0","error":{"code":404,"message":"Not found","data":null},"id":null}
```

All looks good on my side, available to do other tests if needed, otherwise you can close the ticket, solved to me.

**Comment by ZIMkaRU** [comment]
thanks for participating in the debugging, it really helped

**Comment by ezewer** [comment]
Closing the issue as it has been solved
