### ISSUE TITLE
Tax reports do not work

### ISSUE THREAD

**Issue by one4many** [bitfinexcom/bfx-report-electron#238]
The tax reports do not seem to works. Regardless if I work with online or offline queries I get the spinning wheel of dead and a error message pop-up later (see attached image). I can also choose different time frame I want the report from always with the same result.

<img width="1032" alt="Screenshot 2023-08-09 at 14 36 14" src="https://github.com/bitfinexcom/bfx-report-electron/assets/19531845/169ba736-9ed2-40a5-8513-fd36096a748c">

**Comment by ezewer** [comment]
Hi @one4many for tax report query needs to be set as offline. 
We would work in creating something more intuitive

**Comment by one4many** [comment]
Hi @ezewer, thank you for letting me know. But as I stated before, the same error also turn's up in 'offline-mode'.

**Comment by ZIMkaRU** [comment]
Hi @one4many, can I ask you to try to fetch this kind of report (it will make some fresh error logs) and then open a new issue via the menu bar as it's shown on the screenshot? It would attach additional debug info and help to understand where the issue

![Screenshot from 2023-08-15 14-16-26](https://github.com/bitfinexcom/bfx-report-electron/assets/16489235/bbf93e7b-3581-4c9f-bd11-6954509c72ec)

**Comment by one4many** [comment]
@ZIMkaRU here we got ... new issue is open

**Comment by ZIMkaRU** [comment]
thanks
