### ISSUE TITLE
The application "Bitfinex Report" can't be opened - 0.10.3

### ISSUE THREAD

**Issue by user905** [bitfinexcom/bfx-report-electron#35]
This message appears on a MacBook Pro running Catalina (10.15.3). This is not a block in the iOS "Security & Privacy Settings."

Thoughts?

<img width="422" alt="Screen Shot 2020-03-15 at 5 28 15 PM" src="https://user-images.githubusercontent.com/29554021/76711046-bbf10b80-66e2-11ea-8cff-6b62a7e14115.png">

**Comment by ezewer** [comment]
HI @user905 can you please try opening it with right click please? 
Can you confirm if this helps, it should.

**Comment by user905** [comment]
Hey @ezewer - right-click -> open shows the same message.

**Comment by ezewer** [comment]
@user905 this is strange, using same `MacBook Pro running Catalina (10.15.3)`
Can you try deleting this folder `~/Library/Application Support/bfx-report-electron`, folder where was unzipped and unzipped it again please?

**Comment by user905** [comment]
Hmmm - that folder doesn't appear to exist:

![applicationsupport](https://user-images.githubusercontent.com/29554021/77104637-b2bdb280-69f2-11ea-8aea-94952c9b9a18.jpg)

**Comment by ezewer** [comment]
Strange, can try re installing the application please? 
Using this link right? https://github.com/bitfinexcom/bfx-report-electron/releases/download/0.10.3/bfx-report-electron-0.10.3-mac.zip

**Comment by niallone** [comment]
I'm getting the same error - any ideas?

**Comment by ezewer** [comment]
@niallone and @user905 we are working on the solution would be posted next week

**Comment by niallone** [comment]
> @niallone and @user905 we are working on the solution would be posted next week

Legend, thanks!

**Comment by user905** [comment]
Thank you! Just noticed your request to me. Do you still need anything from
me?

**Comment by ezewer** [comment]
@user905 and @niallone this was fixed on last releases https://github.com/bitfinexcom/bfx-report-electron/releases/tag/v0.10.4 please let me know if not working.
