### ISSUE TITLE
Mac OS build keep loading forever 0.10.3

### ISSUE THREAD

**Issue by sbtnc** [bitfinexcom/bfx-report-electron#36]
Hi,

I have manually built the mac electron version successfully, with no errors. After launching the app, then giving "documents folder" permission, the app keeps loading forever.

<img width="354" alt="Screen Shot 2020-03-23 at 3 45 17 PM" src="https://user-images.githubusercontent.com/4548578/77298846-1f4fee80-6d1e-11ea-8b89-8250af425002.png">

I checked ~/Library/Logs/Bitfinex Report folder which stays empty.
Additionally, checking with Little Snitch, the app doesn't make a call at all.

**Comment by ezewer** [comment]
Hi @sbtnc might be the case that you are already running a grenache network on your computer?

**Comment by sbtnc** [comment]
Actually I haven't. 

Additionally, I ran `npm run electron` and it failed:

![Screen Shot 2020-03-24 at 10 40 04 AM](https://user-images.githubusercontent.com/4548578/77395838-de0e1c00-6dbb-11ea-9fe8-62a2fa3c68bb.png)

I then tried `npm rebuild` and `npm install` which didn't help.

node v13.11.0
npm  6.14.3

**Comment by ezewer** [comment]
Ohh right, there is an issue with node greater than 10.X as to create a build.

**Comment by ezewer** [comment]
@sbtnc can you confirm if last fixes solve the issue, please check that README has new instructions on how to proceed.
