### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by Sprkz** [bitfinexcom/bfx-report-electron#98]
An error occurred

```vim
Error: ENOENT: no such file or directory, open 'C:/Users/Player 1/AppData/Roaming/bfx-report-electron/secret-key'
```

---

| Debug info | |
| :--- | :--- |
| Version | 3.5.0 |
| Commit Hash | 41ab2f8a2898216731154cb8621c527a68476eb7 |
| Commit Date | 2021-07-14T06:02:24Z |
| Electron | 13.1.6 |
| Chrome | 91.0.4472.124 |
| Node.js | 14.16.0 |
| V8 | 9.1.269.36-electron.0 |
| OS version | Windows 10 Pro |
| OS release | Windows_NT x64 10.0.19042 |
| CPUs | Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz x 8 |
| RAM | 15.78GB (1.67GB free) |
| App RAM limit | 4095.75Mb (10.79MB used) |

<details>

<summary>Main log</summary>

```vim
[2021-07-14 17:39:41.242] [error] Error: ENOENT: no such file or directory, open 'C:/Users/Player 1/AppData/Roaming/bfx-report-electron/secret-key'

```

</details>

<details>

<summary>Worker errors</summary>

```vim
Log file read error
```

</details>

<details>

<summary>Worker exceptions</summary>

```vim
Log file read error
```

</details>

---

*The issue was opened from the electron app*

**Comment by ZIMkaRU** [comment]
Fix https://github.com/bitfinexcom/bfx-report-electron/pull/99
